services:
  dashboard:
    build:
      context: .
      dockerfile: docker/Dockerfile.dashboard
    network_mode: "host"  # Use host network mode
    volumes:
      - ./llm_responses:/app/llm_responses
      - ./cache:/app/cache
      - ./.env.default:/app/.env.default
    environment:
      - OLLAMA_HOST=localhost
      - OPENAI_API_KEY=${OPENAI_API_KEY:-dummy_key}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-dummy_key}
      - GROQ_API_KEY=${GROQ_API_KEY:-dummy_key}