services:
  dashboard:
    build:
      context: .
      dockerfile: docker/Dockerfile.dashboard
      network: host
    ports:
      - "8050:8050"
    volumes:
      - ./llm_responses:/app/llm_responses
      - ./cache:/app/cache
      - ./.env.default:/app/.env.default
    environment:
      - OLLAMA_HOST=host.docker.internal
      - OPENAI_API_KEY=${OPENAI_API_KEY:-dummy_key}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-dummy_key}
      - GROQ_API_KEY=${GROQ_API_KEY:-dummy_key}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - ai-dashboard-net

networks:
  ai-dashboard-net:
    driver: bridge